name: Build on push or pull request for hooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      
      - name: Install dependencies for hooks
        run: |
          npm install --legacy-peer-deps

      - name: Generate prisma client
        run: |  
          npm run client

      - name: Compile Typesript
        run: |
          npm run buid

      - name: Run the service
        run: |
          npm run start
